(() => {
  const choices = {
    learn:{label:'Use microlearning',title:'Build focused context or give someone a short chance to practice.',text:'Microlearning fits when the learner needs a new mental model, product context, or judgment before the next task. It may include practice, but it does not need to become a complete certification.',signal:'Performance depends on understanding or judgment.',output:'Short module, scenario, demonstration, or guided practice.'},
    use:{label:'Use performance support',title:'Put the answer inside the workflow when recall is not the goal.',text:'Performance support fits when the person already knows the work but needs a reliable prompt, reference, tool, or current source while doing it. The design should reduce searching and memory load.',signal:'The information changes, is detailed, or only matters during the task.',output:'Job aid, dashboard, one-pager, guide, repository, or decision tool.'},
    both:{label:'Connect both',title:'Teach the judgment, then keep the support available for the real task.',text:'Use both when someone needs enough learning to understand the situation and a reusable resource once the work begins. The lesson should point directly to the support instead of treating it as an unrelated download.',signal:'The work requires initial understanding and repeated reference.',output:'Focused learning linked to a maintained point-of-need resource.'}
  };
  const buttons=[...document.querySelectorAll('[data-hub-choice]')];
  const panel=document.querySelector('.hub-choice-panel');
  const render=(button)=>{const data=choices[button.dataset.hubChoice];if(!data)return;buttons.forEach((item)=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active));});panel.classList.remove('choice-step-1','choice-step-2','choice-step-3','is-sequencing');panel.classList.add(`choice-step-${button.dataset.choiceStep}`);requestAnimationFrame(()=>panel.classList.add('is-sequencing'));document.getElementById('hubChoiceLabel').textContent=data.label;document.getElementById('hubChoiceTitle').textContent=data.title;document.getElementById('hubChoiceText').textContent=data.text;document.getElementById('hubChoiceSignal').textContent=data.signal;document.getElementById('hubChoiceOutput').textContent=data.output;};
  buttons.forEach((button)=>button.addEventListener('click',()=>render(button)));
  if(buttons[0]) render(buttons[0]);
})();
