(() => {
  const methods={
    find:{label:'Access',title:'Put the resource where the work already happens.',text:'Performance support loses value when people have to remember where it lives. I reduce searching by placing links, references, and entry points in the workflow they already use.',when:'Where will someone look first while doing the task?',formats:'Entry points, labels, permissions, navigation, and device context.',image:'../../../../assets/icons/pixel/performance-support/find.webp'},
    decide:{label:'Scan',title:'Make the answer faster to scan than to reconstruct from memory.',text:'I structure the resource around the decision, task, or question the user has in the moment. Strong hierarchy, concise language, and visible next actions matter more than adding more content.',when:'What must the user recognize in the first few seconds?',formats:'Chunking, labels, visual hierarchy, progressive detail, and clear actions.',image:'../../../../assets/icons/pixel/performance-support/decide.webp'},
    monitor:{label:'Trust',title:'Make the source, owner, and current state obvious.',text:'People stop using support when they cannot tell whether it is current. I design for source authority, version clarity, exceptions, and ownership so the resource remains dependable.',when:'How will the user know this is the current answer?',formats:'Ownership, source links, dates, exception notes, and version cues.',image:'../../../../assets/icons/pixel/performance-support/monitor.webp'},
    extend:{label:'Maintain',title:'Design updates into the support system from the beginning.',text:'Performance support is operational content. I plan who maintains it, what changes are likely, how updates propagate, and how feedback or recurring friction gets back into the next revision.',when:'Who owns the resource after launch, and what triggers an update?',formats:'Maintenance cadence, feedback loop, reusable source files, and change points.',image:'../../../../assets/icons/pixel/performance-support/extend.webp'}
  };
  const buttons=[...document.querySelectorAll('[data-ps-method]')];
  buttons.forEach((button)=>button.addEventListener('click',()=>{const data=methods[button.dataset.psMethod];buttons.forEach((item)=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active));});document.getElementById('psMethodLabel').textContent=data.label;document.getElementById('psMethodTitle').textContent=data.title;document.getElementById('psMethodText').textContent=data.text;document.getElementById('psMethodWhen').textContent=data.when;document.getElementById('psMethodFormats').textContent=data.formats;document.getElementById('psMethodImage').src=data.image;}));
})();