(() => {
  const methods={
    find:{label:'Find',title:'Put the current answer where the work already happens.',text:'A reference guide, one-pager, or repository should be easier to scan than to remember. Clear labels, ownership, and versioning matter as much as visual polish.',when:'The person knows the task but needs a dependable reference.',formats:'Reference guide, one-pager, checklist, repository.',image:'../../../../assets/icons/pixel/performance-support/find.webp'},
    decide:{label:'Decide',title:'Turn criteria into a tool someone can use in the moment.',text:'Decision support should reveal the criteria, keep the evidence close, and make the next action clear. If practice is also needed, I connect the tool to a focused learning experience.',when:'The task requires consistent judgment more than memorized facts.',formats:'Decision tree, checklist, scoring guide, interactive tool.',image:'../../../../assets/icons/pixel/performance-support/decide.webp'},
    monitor:{label:'Monitor',title:'Show status, exceptions, and follow-up without another manual search.',text:'Dashboards and reporting views should surface what needs attention and make ownership clear. The point is an actionable view, not a decorative chart.',when:'People need to track progress, risk, completion, or exceptions.',formats:'Dashboard, tracker, report, follow-up queue.',image:'../../../../assets/icons/pixel/performance-support/monitor.webp'},
    extend:{label:'Extend',title:'Carry the learning resource into the real workflow.',text:'Formal learning should point to the guide, deck, repository, or tool the person will use later. That connection turns a takeaway into maintained performance support.',when:'A learning program introduces work that continues after the course.',formats:'Linked repository, job aid, manager deck, reference pack.',image:'../../../../assets/icons/pixel/performance-support/extend.webp'}
  };
  const buttons=[...document.querySelectorAll('[data-ps-method]')];
  buttons.forEach((button)=>button.addEventListener('click',()=>{const data=methods[button.dataset.psMethod];buttons.forEach((item)=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active));});document.getElementById('psMethodLabel').textContent=data.label;document.getElementById('psMethodTitle').textContent=data.title;document.getElementById('psMethodText').textContent=data.text;document.getElementById('psMethodWhen').textContent=data.when;document.getElementById('psMethodFormats').textContent=data.formats;document.getElementById('psMethodImage').src=data.image;}));
})();
