from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = ROOT / "portfolio-data"
PROJECT_ROOT = DATA_ROOT / "projects"
TAXONOMY_PATH = DATA_ROOT / "taxonomy.json"
VERSION_PATH = DATA_ROOT / "version.json"
DOCS_ROOT = ROOT / "docs"
VERSIONS_ROOT = DOCS_ROOT / "versions"
INVENTORY_PATH = DOCS_ROOT / "content-inventory.md"
MAP_PATH = DOCS_ROOT / "portfolio-map.md"
CHANGELOG_PATH = DOCS_ROOT / "changelog.md"

SEMVER_PATTERN = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")
CORE_PAGES = [
    ("Home", "portfolio/index.html"),
    ("About Me", "portfolio/about/index.html"),
    ("Projects", "portfolio/projects/index.html"),
    ("Contact", "portfolio/contact/index.html"),
]


def load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"Missing file: {path.relative_to(ROOT)}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Invalid JSON in {path.relative_to(ROOT)}: line {exc.lineno}, column {exc.colno}: {exc.msg}"
        ) from exc


def load_projects() -> list[dict]:
    projects: list[dict] = []
    for path in sorted(PROJECT_ROOT.glob("*.json")):
        project = load_json(path)
        project["_source_path"] = path.relative_to(ROOT).as_posix()
        projects.append(project)
    return projects


def md(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def taxonomy_maps(taxonomy: dict) -> tuple[dict[str, dict], dict[str, str], dict[str, str], dict[str, str]]:
    categories = {item["id"]: item for item in taxonomy.get("categories", [])}
    statuses = {item["id"]: item.get("label", item["id"].title()) for item in taxonomy.get("statuses", [])}
    confidentiality = {
        item["id"]: item.get("label", item["id"].title())
        for item in taxonomy.get("confidentiality", [])
    }
    subcategories: dict[str, str] = {}
    for category in taxonomy.get("categories", []):
        for item in category.get("subcategories", []):
            subcategories[item["id"]] = item.get("label", item["id"].title())
    return categories, statuses, confidentiality, subcategories


def bump_version(version: str, bump: str) -> str:
    match = SEMVER_PATTERN.fullmatch(version)
    if not match:
        raise ValueError(f"Current version is not valid semantic versioning: {version}")
    major, minor, patch = (int(value) for value in match.groups())
    if bump == "major":
        return f"{major + 1}.0.0"
    if bump == "minor":
        return f"{major}.{minor + 1}.0"
    if bump == "patch":
        return f"{major}.{minor}.{patch + 1}"
    raise ValueError(f"Unknown bump type: {bump}")


def status_counts(projects: list[dict], taxonomy: dict) -> dict[str, int]:
    raw = Counter(project.get("status", "unknown") for project in projects)
    ordered: dict[str, int] = {}
    for item in taxonomy.get("statuses", []):
        ordered[item["id"]] = raw.get(item["id"], 0)
    for key in sorted(set(raw) - set(ordered)):
        ordered[key] = raw[key]
    return ordered


def generate_inventory(projects: list[dict], taxonomy: dict, version_data: dict) -> str:
    categories, statuses, confidentiality, subcategories = taxonomy_maps(taxonomy)
    counts = status_counts(projects, taxonomy)
    featured = sum(1 for project in projects if project.get("featured"))
    sanitized = sum(1 for project in projects if project.get("confidentiality") == "sanitized")

    lines = [
        "# Portfolio Content Inventory",
        "",
        "<!-- AUTO-GENERATED by scripts/update-docs.py. Do not edit by hand. -->",
        "",
        f"Current portfolio version: **{md(version_data['current_version'])}**",
        "",
        "## Summary",
        "",
        f"- Structured projects: **{len(projects)}**",
    ]
    for status_id, count in counts.items():
        lines.append(f"- {statuses.get(status_id, status_id.title())}: **{count}**")
    lines.extend(
        [
            f"- Featured projects: **{featured}**",
            f"- Sanitized / fictionalized projects: **{sanitized}**",
            "",
            "## Structured Projects",
            "",
            "| Project | Category | Subcategory | Status | Featured | Confidentiality | Page |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )

    def sort_key(project: dict) -> tuple[str, str, str]:
        category = categories.get(project.get("category"), {})
        return (
            category.get("label", project.get("category", "")),
            subcategories.get(project.get("subcategory"), ""),
            project.get("title", ""),
        )

    for project in sorted(projects, key=sort_key):
        category = categories.get(project.get("category"), {})
        category_label = category.get("label", project.get("category", "Unknown"))
        subcategory_label = subcategories.get(project.get("subcategory"), "—")
        status_label = statuses.get(project.get("status"), project.get("status", "Unknown").title())
        confidentiality_label = confidentiality.get(
            project.get("confidentiality"), project.get("confidentiality", "Unknown").title()
        )
        lines.append(
            "| "
            + " | ".join(
                [
                    md(project.get("title", "Untitled")),
                    md(category_label),
                    md(subcategory_label),
                    md(status_label),
                    "Yes" if project.get("featured") else "No",
                    md(confidentiality_label),
                    f"`{md(project.get('page_path', ''))}`",
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Source Records",
            "",
            "Structured project records are stored under `portfolio-data/projects/`. Public-safe assets are listed in each project record; private/reference source files should not be committed to this public repository.",
            "",
        ]
    )
    return "\n".join(lines)


def generate_map(projects: list[dict], taxonomy: dict, version_data: dict) -> str:
    project_by_category: dict[str, list[dict]] = {}
    for project in projects:
        project_by_category.setdefault(project.get("category", "unknown"), []).append(project)

    all_html = sorted(
        path.relative_to(ROOT).as_posix()
        for path in (ROOT / "portfolio").rglob("*.html")
    )
    known_paths = {path for _, path in CORE_PAGES}
    known_paths.update(project.get("page_path") for project in projects if project.get("page_path"))

    lines = [
        "# Portfolio Map",
        "",
        "<!-- AUTO-GENERATED by scripts/update-docs.py. Do not edit by hand. -->",
        "",
        f"Current portfolio version: **{md(version_data['current_version'])}**",
        "",
        "## Core Pages",
        "",
    ]
    for label, path in CORE_PAGES:
        lines.append(f"- **{label}** — `{path}`")

    lines.extend(["", "## Portfolio Areas", ""])

    for category in taxonomy.get("categories", []):
        category_path = category.get("path")
        if category_path:
            known_paths.add(category_path)
            lines.append(f"- **{category['label']}** — `{category_path}`")
        else:
            lines.append(f"- **{category['label']}**")

        subcategory_projects: dict[str | None, list[dict]] = {}
        for project in project_by_category.get(category["id"], []):
            subcategory_projects.setdefault(project.get("subcategory"), []).append(project)

        subcategory_ids: set[str] = set()
        for subcategory in category.get("subcategories", []):
            subcategory_ids.add(subcategory["id"])
            subcategory_path = subcategory.get("path")
            if subcategory_path:
                known_paths.add(subcategory_path)
                lines.append(f"  - **{subcategory['label']}** — `{subcategory_path}`")
            else:
                lines.append(f"  - **{subcategory['label']}**")
            for project in sorted(subcategory_projects.get(subcategory["id"], []), key=lambda item: item.get("title", "")):
                lines.append(
                    f"    - {project['title']} — `{project['page_path']}` ({project['status']})"
                )

        for project in sorted(subcategory_projects.get(None, []), key=lambda item: item.get("title", "")):
            lines.append(f"  - {project['title']} — `{project['page_path']}` ({project['status']})")

        unknown_subcategories = sorted(set(subcategory_projects) - subcategory_ids - {None})
        for subcategory_id in unknown_subcategories:
            lines.append(f"  - **{subcategory_id}**")
            for project in sorted(subcategory_projects[subcategory_id], key=lambda item: item.get("title", "")):
                lines.append(f"    - {project['title']} — `{project['page_path']}` ({project['status']})")

    other_pages = [path for path in all_html if path not in known_paths]
    lines.extend(["", "## Other Public HTML Pages", ""])
    if other_pages:
        lines.append(
            "These pages exist in the public site but are not represented by a structured project record or canonical taxonomy page."
        )
        lines.append("")
        for path in other_pages:
            lines.append(f"- `{path}`")
    else:
        lines.append("None.")

    lines.extend(["", f"Total public HTML pages: **{len(all_html)}**", ""])
    return "\n".join(lines)


def generate_changelog(version_data: dict) -> str:
    lines = [
        "# Portfolio Changelog",
        "",
        "<!-- AUTO-GENERATED by scripts/update-docs.py. Do not edit by hand. -->",
        "",
        f"Current version: **{md(version_data['current_version'])}**",
        "",
    ]
    for release in version_data.get("releases", []):
        lines.extend(
            [
                f"## {md(release['version'])} — {md(release['date'])}",
                "",
                f"- {md(release['summary'])}",
                "",
            ]
        )
    return "\n".join(lines)


def generate_snapshot(version: str, release: dict, projects: list[dict], taxonomy: dict) -> str:
    counts = status_counts(projects, taxonomy)
    status_labels = {
        item["id"]: item.get("label", item["id"].title())
        for item in taxonomy.get("statuses", [])
    }
    html_count = sum(1 for _ in (ROOT / "portfolio").rglob("*.html"))
    lines = [
        f"# Portfolio Version {version}",
        "",
        f"Date: **{md(release['date'])}**",
        "",
        f"{md(release['summary'])}",
        "",
        "## Snapshot",
        "",
        f"- Structured projects: **{len(projects)}**",
        f"- Public HTML pages: **{html_count}**",
    ]
    for status_id, count in counts.items():
        lines.append(f"- {status_labels.get(status_id, status_id.title())}: **{count}**")
    lines.extend(["", "## Structured Projects", ""])
    for project in sorted(projects, key=lambda item: item.get("title", "")):
        lines.append(
            f"- **{md(project['title'])}** — `{md(project['page_path'])}` ({md(project['status'])})"
        )
    lines.append("")
    return "\n".join(lines)


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(path.suffix + ".tmp")
    temp_path.write_text(content, encoding="utf-8")
    temp_path.replace(path)


def build_outputs(projects: list[dict], taxonomy: dict, version_data: dict) -> dict[Path, str]:
    return {
        INVENTORY_PATH: generate_inventory(projects, taxonomy, version_data),
        MAP_PATH: generate_map(projects, taxonomy, version_data),
        CHANGELOG_PATH: generate_changelog(version_data),
    }


def apply_bump(version_data: dict, bump: str, summary: str, release_date: str) -> dict:
    updated = json.loads(json.dumps(version_data))
    current = updated.get("current_version", "0.0.0")
    next_version = bump_version(current, bump)
    updated["current_version"] = next_version
    updated.setdefault("releases", []).insert(
        0,
        {
            "version": next_version,
            "date": release_date,
            "bump": bump,
            "summary": summary.strip(),
        },
    )
    return updated


def check_outputs(outputs: dict[Path, str], version_data: dict) -> list[str]:
    stale: list[str] = []
    for path, expected in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path.relative_to(ROOT).as_posix())
    snapshot_path = VERSIONS_ROOT / f"v{version_data['current_version']}.md"
    if not snapshot_path.exists():
        stale.append(snapshot_path.relative_to(ROOT).as_posix())
    return stale


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Regenerate portfolio documentation and optionally create a semantic version release."
    )
    parser.add_argument("--bump", choices=["patch", "minor", "major"], help="Create a new portfolio version.")
    parser.add_argument("--message", help="Release summary required when --bump is used.")
    parser.add_argument("--date", dest="release_date", help="Release date in YYYY-MM-DD format. Defaults to today.")
    parser.add_argument("--check", action="store_true", help="Fail if generated documentation is stale.")
    parser.add_argument("--dry-run", action="store_true", help="Preview what would change without writing files.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.check and (args.bump or args.dry_run):
        print("ERROR: --check cannot be combined with --bump or --dry-run.")
        return 1
    if args.bump and not (args.message and args.message.strip()):
        print("ERROR: --message is required when --bump is used.")
        return 1
    if args.message and not args.bump:
        print("ERROR: --message is only used with --bump.")
        return 1

    try:
        taxonomy = load_json(TAXONOMY_PATH)
        projects = load_projects()
        version_data = load_json(VERSION_PATH)
        if args.bump:
            version_data = apply_bump(
                version_data,
                args.bump,
                args.message,
                args.release_date or date.today().isoformat(),
            )
        outputs = build_outputs(projects, taxonomy, version_data)
    except (ValueError, KeyError) as exc:
        print(f"ERROR: {exc}")
        return 1

    if args.check:
        stale = check_outputs(outputs, version_data)
        if stale:
            print("Generated documentation is stale:")
            for path in stale:
                print(f"  - {path}")
            print("Run: python3 scripts/update-docs.py")
            return 1
        print("Generated documentation is current.")
        return 0

    changed_paths = [path.relative_to(ROOT).as_posix() for path in outputs]
    if args.bump:
        changed_paths.extend(
            [
                VERSION_PATH.relative_to(ROOT).as_posix(),
                (VERSIONS_ROOT / f"v{version_data['current_version']}.md").relative_to(ROOT).as_posix(),
            ]
        )

    if args.dry_run:
        print(f"Current/next version: {version_data['current_version']}")
        print("Would update:")
        for path in changed_paths:
            print(f"  - {path}")
        return 0

    for path, content in outputs.items():
        atomic_write(path, content)

    if args.bump:
        atomic_write(VERSION_PATH, json.dumps(version_data, indent=2, ensure_ascii=False) + "\n")
        release = version_data["releases"][0]
        snapshot_path = VERSIONS_ROOT / f"v{version_data['current_version']}.md"
        atomic_write(snapshot_path, generate_snapshot(version_data["current_version"], release, projects, taxonomy))

    print(f"Documentation updated for portfolio version {version_data['current_version']}.")
    if args.bump:
        print(f"Created release snapshot: docs/versions/v{version_data['current_version']}.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
